const db = require('../config/connection');
const {User, Unit, Waitlist} = require('../models');

db.once('open', async()=>{
    await Unit.deleteMany();

    const units = await Unit.insertMany([
        {number:'A1',location:'Heritage',status:'Available'},
        {number:'A2',location:'Heritage',status:'Available'},
        {number:'A3',location:'Heritage',status:'Available'},
        {number:'A4',location:'Heritage',status:'Available'},
        {number:'A5',location:'Heritage',status:'Available'},
        {number:'A6',location:'Heritage',status:'Available'},
        {number:'A7',location:'Heritage',status:'Available'},
        {number:'A8',location:'Heritage',status:'Available'},
        {number:'A9',location:'Heritage',status:'Available'},
        {number:'A10',location:'Heritage',status:'Available'},
        {number:'A11',location:'Heritage',status:'Available'},
        {number:'A12',location:'Heritage',status:'Available'},
        {number:'A13',location:'Heritage',status:'Available'},
        {number:'A14',location:'Heritage',status:'Available'},
        {number:'A15',location:'Heritage',status:'Available'},
        {number:'A16',location:'Heritage',status:'Available'},
        {number:'A17',location:'Heritage',status:'Available'},
        {number:'A18',location:'Heritage',status:'Available'},
        {number:'A19',location:'Heritage',status:'Available'},
        {number:'A20',location:'Heritage',status:'Available'},
        {number:'B1',location:'Heritage',status:'Available'},
        {number:'B2',location:'Heritage',status:'Available'},
        {number:'B3',location:'Heritage',status:'Available'},
        {number:'B4',location:'Heritage',status:'Available'},
        {number:'B5',location:'Heritage',status:'Available'},
        {number:'B6',location:'Heritage',status:'Available'},
        {number:'B7',location:'Heritage',status:'Available'},
        {number:'B8',location:'Heritage',status:'Available'},
        {number:'B9',location:'Heritage',status:'Available'},
        {number:'B10',location:'Heritage',status:'Available'},
        {number:'B11',location:'Heritage',status:'Available'},
        {number:'B12',location:'Heritage',status:'Available'},
        {number:'B13',location:'Heritage',status:'Available'},
        {number:'B14',location:'Heritage',status:'Available'},
        {number:'B15',location:'Heritage',status:'Available'},
        {number:'B16',location:'Heritage',status:'Available'},
        {number:'B17',location:'Heritage',status:'Available'},
        {number:'B18',location:'Heritage',status:'Available'},
        {number:'B19',location:'Heritage',status:'Available'},
        {number:'B20',location:'Heritage',status:'Available'},
        {number:'C1',location:'Heritage',status:'Available'},
        {number:'C2',location:'Heritage',status:'Available'},
        {number:'C3',location:'Heritage',status:'Available'},
        {number:'C4',location:'Heritage',status:'Available'},
        {number:'C5',location:'Heritage',status:'Available'},
        {number:'C6',location:'Heritage',status:'Available'},
        {number:'C7',location:'Heritage',status:'Available'},
        {number:'C8',location:'Heritage',status:'Available'},
        {number:'C9',location:'Heritage',status:'Available'},
        {number:'C10',location:'Heritage',status:'Available'},
        {number:'C11',location:'Heritage',status:'Available'},
        {number:'C12',location:'Heritage',status:'Available'},
        {number:'C13',location:'Heritage',status:'Available'},
        {number:'C14',location:'Heritage',status:'Available'},
        {number:'C15',location:'Heritage',status:'Available'},
        {number:'C16',location:'Heritage',status:'Available'},
        {number:'C17',location:'Heritage',status:'Available'},
        {number:'C18',location:'Heritage',status:'Available'},
        {number:'C19',location:'Heritage',status:'Available'},
        {number:'C20',location:'Heritage',status:'Available'},
        {number:'C21',location:'Heritage',status:'Available'},
        {number:'C22',location:'Heritage',status:'Available'},
        {number:'C23',location:'Heritage',status:'Available'},
        {number:'C24',location:'Heritage',status:'Available'},
        {number:'C25',location:'Heritage',status:'Available'},
        {number:'C26',location:'Heritage',status:'Available'},
        {number:'D1',location:'Heritage',status:'Available'},
        {number:'D2',location:'Heritage',status:'Available'},
        {number:'D3',location:'Heritage',status:'Available'},
        {number:'D4',location:'Heritage',status:'Available'},
        {number:'D5',location:'Heritage',status:'Available'},
        {number:'D6',location:'Heritage',status:'Available'},
        {number:'D7',location:'Heritage',status:'Available'},
        {number:'D8',location:'Heritage',status:'Available'},
        {number:'D9',location:'Heritage',status:'Available'},
        {number:'D10',location:'Heritage',status:'Available'},
        {number:'D11',location:'Heritage',status:'Available'},
        {number:'D12',location:'Heritage',status:'Available'},
        {number:'D13',location:'Heritage',status:'Available'},
        {number:'D14',location:'Heritage',status:'Available'},
        {number:'D15',location:'Heritage',status:'Available'},
        {number:'D16',location:'Heritage',status:'Available'},
        {number:'D17',location:'Heritage',status:'Available'},
        {number:'D18',location:'Heritage',status:'Available'},
        {number:'D19',location:'Heritage',status:'Available'},
        {number:'D20',location:'Heritage',status:'Available'},
        {number:'D21',location:'Heritage',status:'Available'},
        {number:'D22',location:'Heritage',status:'Available'},
        {number:'D23',location:'Heritage',status:'Available'},
        {number:'D24',location:'Heritage',status:'Available'},
        {number:'D25',location:'Heritage',status:'Available'},
        {number:'D26',location:'Heritage',status:'Available'},
        {number:'E1',location:'Heritage',status:'Available'},
        {number:'E2',location:'Heritage',status:'Available'},
        {number:'E3',location:'Heritage',status:'Available'},
        {number:'E4',location:'Heritage',status:'Available'},
        {number:'E5',location:'Heritage',status:'Available'},
        {number:'E6',location:'Heritage',status:'Available'},
        {number:'E7',location:'Heritage',status:'Available'},
        {number:'E8',location:'Heritage',status:'Available'},
        {number:'E9',location:'Heritage',status:'Available'},
        {number:'E10',location:'Heritage',status:'Available'},
        {number:'E11',location:'Heritage',status:'Available'},
        {number:'E12',location:'Heritage',status:'Available'},
        {number:'E13',location:'Heritage',status:'Available'},
        {number:'E14',location:'Heritage',status:'Available'},
        {number:'E15',location:'Heritage',status:'Available'},
        {number:'E16',location:'Heritage',status:'Available'},
        {number:'E17',location:'Heritage',status:'Available'},
        {number:'E18',location:'Heritage',status:'Available'},
        {number:'E19',location:'Heritage',status:'Available'},
        {number:'E20',location:'Heritage',status:'Available'},
        {number:'E21',location:'Heritage',status:'Available'},
        {number:'F1',location:'Heritage',status:'Available'},
        {number:'F2',location:'Heritage',status:'Available'},
        {number:'F3',location:'Heritage',status:'Available'},
        {number:'F4',location:'Heritage',status:'Available'},
        {number:'F5',location:'Heritage',status:'Available'},
        {number:'F6',location:'Heritage',status:'Available'},
        {number:'F7',location:'Heritage',status:'Available'},
        {number:'F8',location:'Heritage',status:'Available'},
        {number:'F9',location:'Heritage',status:'Available'},
        {number:'F10',location:'Heritage',status:'Available'},
        {number:'F11',location:'Heritage',status:'Available'},
        {number:'F12',location:'Heritage',status:'Available'},
        {number:'F13',location:'Heritage',status:'Available'},
        {number:'F14',location:'Heritage',status:'Available'},
        {number:'F15',location:'Heritage',status:'Available'},
        {number:'F16',location:'Heritage',status:'Available'},
        {number:'F17',location:'Heritage',status:'Available'},
        {number:'F18',location:'Heritage',status:'Available'},
        {number:'F19',location:'Heritage',status:'Available'},
        {number:'F20',location:'Heritage',status:'Available'},
        {number:'F21',location:'Heritage',status:'Available'},
        {number:'F22',location:'Heritage',status:'Available'},
        {number:'F23',location:'Heritage',status:'Available'},
        {number:'F24',location:'Heritage',status:'Available'},
        {number:'F25',location:'Heritage',status:'Available'},
        {number:'F26',location:'Heritage',status:'Available'},
        {number:'F27',location:'Heritage',status:'Available'},
        {number:'F28',location:'Heritage',status:'Available'},
        {number:'G1',location:'Heritage',status:'Available'},
        {number:'G2',location:'Heritage',status:'Available'},
        {number:'G3',location:'Heritage',status:'Available'},
        {number:'G4',location:'Heritage',status:'Available'},
        {number:'G5',location:'Heritage',status:'Available'},
        {number:'G6',location:'Heritage',status:'Available'},
        {number:'G7',location:'Heritage',status:'Available'},
        {number:'G8',location:'Heritage',status:'Available'},
        {number:'G9',location:'Heritage',status:'Available'},
        {number:'G10',location:'Heritage',status:'Available'},
        {number:'G11',location:'Heritage',status:'Available'},
        {number:'G12',location:'Heritage',status:'Available'},
        {number:'G13',location:'Heritage',status:'Available'},
        {number:'G14',location:'Heritage',status:'Available'},
        {number:'G15',location:'Heritage',status:'Available'},
        {number:'G16',location:'Heritage',status:'Available'},
        {number:'G17',location:'Heritage',status:'Available'},
        {number:'G18',location:'Heritage',status:'Available'},
        {number:'G19',location:'Heritage',status:'Available'},
        {number:'G20',location:'Heritage',status:'Available'},
        {number:'G21',location:'Heritage',status:'Available'},
        {number:'G22',location:'Heritage',status:'Available'},
        {number:'G23',location:'Heritage',status:'Available'},
        {number:'G24',location:'Heritage',status:'Available'},
        {number:'G25',location:'Heritage',status:'Available'},
        {number:'G26',location:'Heritage',status:'Available'},
        {number:'G27',location:'Heritage',status:'Available'},
        {number:'G28',location:'Heritage',status:'Available'},
        {number:'H1',location:'Heritage',status:'Available'},
        {number:'H2',location:'Heritage',status:'Available'},
        {number:'H3',location:'Heritage',status:'Available'},
        {number:'H4',location:'Heritage',status:'Available'},
        {number:'H5',location:'Heritage',status:'Available'},
        {number:'H6',location:'Heritage',status:'Available'},
        {number:'H7',location:'Heritage',status:'Available'},
        {number:'H8',location:'Heritage',status:'Available'},
        {number:'H9',location:'Heritage',status:'Available'},
        {number:'H10',location:'Heritage',status:'Available'},
        {number:'H11',location:'Heritage',status:'Available'},
        {number:'H12',location:'Heritage',status:'Available'},
        {number:'H13',location:'Heritage',status:'Available'},
        {number:'H14',location:'Heritage',status:'Available'},
        {number:'H15',location:'Heritage',status:'Available'},
        {number:'H16',location:'Heritage',status:'Available'},
        {number:'H17',location:'Heritage',status:'Available'},
        {number:'H18',location:'Heritage',status:'Available'},
        {number:'H19',location:'Heritage',status:'Available'},
        {number:'H20',location:'Heritage',status:'Available'},
        {number:'H21',location:'Heritage',status:'Available'},
        {number:'H22',location:'Heritage',status:'Available'},
        {number:'H23',location:'Heritage',status:'Available'},
        {number:'H24',location:'Heritage',status:'Available'},
        {number:'H25',location:'Heritage',status:'Available'},
        {number:'H26',location:'Heritage',status:'Available'},
        {number:'H27',location:'Heritage',status:'Available'},
        {number:'H28',location:'Heritage',status:'Available'},
        {number:'1',location:'Hometown',status:'Available'},
        {number:'2',location:'Hometown',status:'Available'},
        {number:'3',location:'Hometown',status:'Available'},
        {number:'4',location:'Hometown',status:'Available'},
        {number:'5',location:'Hometown',status:'Available'},
        {number:'6',location:'Hometown',status:'Available'},
        {number:'7',location:'Hometown',status:'Available'},
        {number:'8',location:'Hometown',status:'Available'},
        {number:'9',location:'Hometown',status:'Available'},
        {number:'10',location:'Hometown',status:'Available'},
        {number:'11',location:'Hometown',status:'Available'},
        {number:'12',location:'Hometown',status:'Available'},
        {number:'13',location:'Hometown',status:'Available'},
        {number:'14',location:'Hometown',status:'Available'},
        {number:'15',location:'Hometown',status:'Available'},
        {number:'16',location:'Hometown',status:'Available'},
        {number:'17',location:'Hometown',status:'Available'},
        {number:'18',location:'Hometown',status:'Available'},
        {number:'19',location:'Hometown',status:'Available'},
        {number:'20',location:'Hometown',status:'Available'},
        {number:'21',location:'Hometown',status:'Available'},
        {number:'22',location:'Hometown',status:'Available'},
        {number:'23',location:'Hometown',status:'Available'},
        {number:'24',location:'Hometown',status:'Available'},
        {number:'25',location:'Hometown',status:'Available'},
        {number:'26',location:'Hometown',status:'Available'},
        {number:'27',location:'Hometown',status:'Available'},
        {number:'28',location:'Hometown',status:'Available'},
        {number:'29',location:'Hometown',status:'Available'},
        {number:'30',location:'Hometown',status:'Available'},
        {number:'31',location:'Hometown',status:'Available'},
        {number:'32',location:'Hometown',status:'Available'},
        {number:'33',location:'Hometown',status:'Available'},
        {number:'34',location:'Hometown',status:'Available'},
        {number:'35',location:'Hometown',status:'Available'},
        {number:'36',location:'Hometown',status:'Available'},
        {number:'37',location:'Hometown',status:'Available'},
        {number:'38',location:'Hometown',status:'Available'},
        {number:'39',location:'Hometown',status:'Available'},
        {number:'40',location:'Hometown',status:'Available'},
        {number:'41',location:'Hometown',status:'Available'},
        {number:'42',location:'Hometown',status:'Available'},
        {number:'43',location:'Hometown',status:'Available'},
        {number:'44',location:'Hometown',status:'Available'},
        {number:'45',location:'Hometown',status:'Available'},
        {number:'46',location:'Hometown',status:'Available'},
        {number:'47',location:'Hometown',status:'Available'},
        {number:'48',location:'Hometown',status:'Available'},
        {number:'49',location:'Hometown',status:'Available'},
        {number:'50',location:'Hometown',status:'Available'},
        {number:'51',location:'Hometown',status:'Available'},
        {number:'52',location:'Hometown',status:'Available'},
        {number:'53',location:'Hometown',status:'Available'},
        {number:'54',location:'Hometown',status:'Available'},
        {number:'55',location:'Hometown',status:'Available'},
        {number:'56',location:'Hometown',status:'Available'},
        {number:'57',location:'Hometown',status:'Available'},
        {number:'58',location:'Hometown',status:'Available'},
        {number:'59',location:'Hometown',status:'Available'},
        {number:'60',location:'Hometown',status:'Available'},
        {number:'61',location:'Hometown',status:'Available'},
        {number:'62',location:'Hometown',status:'Available'},
        {number:'63',location:'Hometown',status:'Available'},
        {number:'64',location:'Hometown',status:'Available'},
        {number:'65',location:'Hometown',status:'Available'},
        {number:'66',location:'Hometown',status:'Available'},
        {number:'67',location:'Hometown',status:'Available'},
    ]);
    console.log('units seeded');

    // await User.deleteMany();

    // await User.create({
    //     first_name:'Elizabeth',
    //     last_name:'Sherrow',
    //     address:'1234 North St',
    //     phone:'123456789',
    //     email:'test@email.com',
    //     password:'s&l2021',
    // });
    // console.log('users seeded');

    // await Waitlist.deleteMany();

    // await Waitlist.create({
    //     first_name:'Elizabeth',
    //     last_name:'Sherrow',
    //     phone:'123456789',
    //     email:'test@email.com',
    //     location:'Hometown',
    //     size:"5' x 10'"

    // });
    // console.log('waitlist seeded');
    process.exit(0)
});